### ISSUE TITLE
YouTube videos aren't responsive

### ISSUE THREAD

**Issue by jaydanurwin** [jamesqquick/jamesqquick-site#56]
It looks like the YouTube videos aren't fully responsive quite yet. I would recommend aspect ratio with a fallback. I know how to do this in vanilla css but I see you're using tailwind so this might help 

https://tailwindcss.com/docs/aspect-ratio

![Screenshot_20220909-084656](https://user-images.githubusercontent.com/42281662/189379095-7eb82e00-0149-4736-a6a8-102f6c6799b1.png)

**Comment by jamesqquick** [comment]
Got it fixed. Thanks so much for calling this out!
